# Generated by Django 4.2.15 on 2025-10-16 14:57

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                default="+16048616603",
                max_length=30,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
    ]
